### ISSUE TITLE
Ganglion Not Writing to SD card

### ISSUE THREAD

**Issue by nrutherf** [OpenBCI/OpenBCI_Ganglion_SD#1]
Hi there,

I've been trying to get my Ganglion Board to write to SD Card with no success. I've tried updating the firmware with the current version on github (https://github.com/OpenBCI/OpenBCI_Ganglion_Library) combined with the companion SD Card Library (https://github.com/OpenBCI/OpenBCI_Ganglion_SD). I'm using this SD Card (https://www.amazon.co.uk/Transcend-Extreme-Speed-Micro-Memory-Class/dp/B004W63RT4/ref=sr_1_3?ie=UTF8&qid=1503656599&sr=8-3&keywords=transcend+4gb+sd+card). I've been testing sending commands to the board using the nodeJS library (https://github.com/OpenBCI/OpenBCI_NodeJS_Ganglion) and have been able to send commands such as start and stop stream. However, if I send the commands to start and stop writing to the card, the card is empty when I check it.

Any thoughts on this issue would be appreciated!

Thanks,

Nathan

**Comment by biomurph** [comment]
Hi,
We have not done much work with the SD card since last spring when we discovered that writing to the card causes noise in the system. The noise is not huge (~2-3uV) but it appears at may frequencies. I'm not sure if the nodeJS is setup to do that. @aj-ptw might have some insight

**Comment by andrewjaykeller** [comment]
All we would have to do is send a command right? Do you need a function to call? You can do a `ganglion.write("A")` for example and that sound work if you have the right firmware loaded on!

**Comment by andrewjaykeller** [comment]
Shouldn't he be using the main library and just use the example with sd?

AJ Keller
Push The World

**Comment by nrutherf** [comment]
That was my line of thinking, I've tried sending the `ganglion.write("A")` and `ganglion.write("j")` commands to the board with no success. However `ganglion.write("b")` and other commands work fine. In relation to the firmware, I've loaded the firmware from https://github.com/OpenBCI/OpenBCI_Ganglion_Library (using the example with SD) and this repos SD Card library onto the board OTA following this tutorial http://docs.openbci.com/Hardware/09-Ganglion_Programming_Tutorial and it seems to have loaded alright, however still no SD Card writing.

**Comment by biomurph** [comment]
We ran into issues with writing to the SD card in development. Not that we couldn't but when we did, there was noise in the signal. See the picture below. In testing, we mainly sent the command to open the SD and create a file via a serial connection on the bench. As soon as it became clear that the SD card write was problematic we kind of set it aside. We may be able to overcome the noise in the future, but we still have to track down exactly where it's coming from. Our theory is that, because the Simblee can't drive the SPI SCLK frequency higher than 4MHz, the 512 byte block write time is causing the noise to occur. Definitely needs more detective work.
<img width="1025" alt="ganglion sd write" src="https://user-images.githubusercontent.com/6284057/29724835-1fe5f4a0-8998-11e7-8f65-3b60a6915f98.png">

**Comment by nrutherf** [comment]
I see. Do you know if it would still be possible to send to command wirelessly to the board to begin writing to SD regardless of the noise that would ensue? Also, do you know if this is also an issue with the Cyton board, or can it write to SD without any issues?

**Comment by biomurph** [comment]
The Cyton board will write to SD without any issues. Cyton drives the SPI SCLK at 20MHz when interfacing the SDcard. 
You should be able to send the command wirelessly to control the SD card write on the Ganglion. I'm not sure why this is not working, however it is likely something in the Hub, the interface between the GUI and the computer BLE. I will make an issue out of it on the GUI repo.

**Comment by shibshib** [comment]
Biomurph that's a really interesting FFT graph there, how come the peaks are all even?

**Comment by xdrouot** [comment]
I think it's the noise and its harmonics, right ?

**Comment by biomurph** [comment]
@xdrouot it is not noise in the harmonics. The problem is that the Simblee, which is doing all of the heavy lifting on the Ganglion is not able to run the SPI bus at a rate fast enough to write to the SD card without overrunning the sample rate of the data acquisition system. We didn't know this would happen when we designed it, but left the SD card holder on anyway, because it is a Kickstarter reward and we said we would include it.
